name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: "npm install"

      - name: Build step
        run: "DATABASE_URL=\"postgresql://file_base_owner:npg_aEqRbGQtn67T@ep-calm-tree-a5k7x5ga-pooler.us-east-2.aws.neon.tech/file_base?sslmode=require\" npx prisma generate; DATABASE_URL=\"postgresql://file_base_owner:npg_aEqRbGQtn67T@ep-calm-tree-a5k7x5ga-pooler.us-east-2.aws.neon.tech/file_base?sslmode=require\" npx prisma db push;"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "filebase"
          entrypoint: "app.js"
          root: ""
          
          
